
ARG NGEN_BASE_IMAGE="ghcr.io/ngwpc/ngen:latest"
FROM $NGEN_BASE_IMAGE AS ngen_rte_base

### Static args
ARG PYTHON_ENV="/ngen-app/ngen-python/bin"
ARG PYTHON_VERSION_STR="python3.11"
ENV PIP_NO_CACHE_DIR=1
ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

COPY nwm-rte/add_git_info.py .

### Create directory for git info JSON files
RUN mkdir -p /ngen-app/git-info

### Activate the venv
ENV PATH="${PYTHON_ENV}:${PATH}"
RUN python -m pip install --upgrade pip

### For VS Code debugger
# RUN pip install debugpy
# RUN dnf install -y gdb


### Install nwm packages

ARG REPO_TAG_FCST_MGR
RUN --mount=type=bind,src=nwm-rte/install_package.sh,dst=/src_ngwpc/nwm-rte/install_package.sh \
    --mount=type=bind,src=nwm-fcst-mgr,dst=/src_ngwpc/nwm-fcst-mgr \
    "/src_ngwpc/nwm-rte/install_package.sh" "python" "nwm-fcst-mgr" "${REPO_TAG_FCST_MGR}" ""

ARG REPO_TAG_MSW_MGR
RUN --mount=type=bind,src=nwm-rte/install_package.sh,dst=/src_ngwpc/nwm-rte/install_package.sh \
    --mount=type=bind,src=nwm-msw-mgr,dst=/src_ngwpc/nwm-msw-mgr \
    "/src_ngwpc/nwm-rte/install_package.sh" "python" "nwm-msw-mgr" "${REPO_TAG_MSW_MGR}" ""

ARG REPO_TAG_CAL_MGR
RUN --mount=type=bind,src=nwm-rte/install_package.sh,dst=/src_ngwpc/nwm-rte/install_package.sh \
    --mount=type=bind,src=nwm-cal-mgr,dst=/src_ngwpc/nwm-cal-mgr \
    "/src_ngwpc/nwm-rte/install_package.sh" "python" "nwm-cal-mgr" "${REPO_TAG_CAL_MGR}" ""

ARG REPO_TAG_REGION_MGR
RUN --mount=type=bind,src=nwm-rte/install_package.sh,dst=/src_ngwpc/nwm-rte/install_package.sh \
    --mount=type=bind,src=nwm-region-mgr,dst=/src_ngwpc/nwm-region-mgr \
    "/src_ngwpc/nwm-rte/install_package.sh" "python" "nwm-region-mgr" "${REPO_TAG_REGION_MGR}" "[parreg]"

ARG REPO_TAG_DATA_ASSIM_ENGINE
RUN --mount=type=bind,src=nwm-rte/install_package.sh,dst=/src_ngwpc/nwm-rte/install_package.sh \
    --mount=type=bind,src=data-assimilation-engine,dst=/src_ngwpc/data-assimilation-engine \
    "/src_ngwpc/nwm-rte/install_package.sh" "python" "data-assimilation-engine" "${REPO_TAG_DATA_ASSIM_ENGINE}" ""

## ngen-forcing package is included with the starting base image,
## but it can be reinstalled from another branch or from local, like the other packages.
ARG REPO_TAG_NGEN_FORCING
RUN --mount=type=bind,src=nwm-rte/install_package.sh,dst=/src_ngwpc/nwm-rte/install_package.sh \
    --mount=type=bind,src=ngen-forcing,dst=/src_ngwpc/ngen-forcing \
    "/src_ngwpc/nwm-rte/install_package.sh" "python" "ngen-forcing" "${REPO_TAG_NGEN_FORCING}" ""
## NOTE if installing ngen-forcing from local and editing additional package "nextgen_forcings_ewts",
## then need this below RUN as well, until this additional ewts package can be incorporated into the top-level pip install.
# COPY "ngen-forcing/" "/tmp/ngen-forcing/"
# RUN python -m pip install "/tmp/ngen-forcing/nextgen_forcings_ewts/"


##################################################
#### BEGIN SECOND STAGE: Adding a separate Python venv for nwm.eval and nwm.verf
FROM ngen_rte_base AS ngen_rte_eval_verf

# Call modules like `python_eval_verf -m nwm.verf`
ARG EVAL_VERF_PYTHON_ALIAS="python_eval_verf"
ARG EVAL_VERF_VENV="/ngen-app/venvs/eval_verf"
ARG EVAL_VERF_PYTHON_BIN_DIR="${EVAL_VERF_VENV}/bin"
ARG EVAL_VERF_PYTHON_BIN_FILE="${EVAL_VERF_PYTHON_BIN_DIR}/python"

# Make the venv
RUN python -m venv "${EVAL_VERF_VENV}"
# Add an alias for convenience
RUN echo "alias ${EVAL_VERF_PYTHON_ALIAS}=\"${EVAL_VERF_PYTHON_BIN_FILE}\"" >> ~/.bashrc

# Save the current PATH and PYTHONPATH
ENV PATH_SAVED=${PATH}
ENV PYTHONPATH_SAVED=${PYTHONPATH}
# Adjust PATH and PYTHONPATH to give this environment precedent
ENV PATH="${EVAL_VERF_PYTHON_BIN_DIR}:${PATH}"
ENV PYTHONPATH="${EVAL_VERF_PYTHON_BIN_DIR}/lib/python3.11/site-packages"

ARG REPO_TAG_VERF
RUN --mount=type=bind,src=nwm-rte/install_package.sh,dst=/src_ngwpc/nwm-rte/install_package.sh \
    --mount=type=bind,src=ngen-forcing,dst=/src_ngwpc/ngen-forcing \
    "/src_ngwpc/nwm-rte/install_package.sh" "/ngen-app/venvs/eval_verf/bin/python" "nwm-verf" "${REPO_TAG_VERF}" ""

ARG REPO_TAG_EVAL
RUN --mount=type=bind,src=nwm-rte/install_package.sh,dst=/src_ngwpc/nwm-rte/install_package.sh \
    --mount=type=bind,src=ngen-forcing,dst=/src_ngwpc/ngen-forcing \
    "/src_ngwpc/nwm-rte/install_package.sh" "/ngen-app/venvs/eval_verf/bin/python" "nwm-eval-mgr" "${REPO_TAG_EVAL}" ""

##############################
#### Clean up: reset PATH and PYTHONPATH
ENV PATH=${PATH_SAVED}
ENV PYTHONPATH=${PYTHONPATH_SAVED}
