# 
# TODO add {}_git_info.json for each dependency repo (other repos do this in their Dockerfile).
# TODO have remote vs local be parameterized in config file rather than requiring switching comment blocks here.
# 


ARG NGEN_BASE_IMAGE="ghcr.io/ngwpc/ngen:latest"
FROM $NGEN_BASE_IMAGE

### Additional user args, these have to be after the FROM
ARG REPO_TAG__FCST_MGR
ARG REPO_TAG__MSW_MGR
ARG REPO_TAG__CAL_MGR
ARG REPO_TAG__REGION_MGR
ARG REPO_TAG__VERF_MGR
ARG REPO_TAG__EVAL_MGR

### Static args
ARG PYTHON_ENV="/ngen-app/ngen-python/bin"
ARG GITHUB_ORG_URL="https://github.com/NGWPC"
ARG GITHUBUSERCONTENT_ORG_URL="https://raw.githubusercontent.com/NGWPC"
ARG REPO_NAME__FCST_MGR="nwm-fcst-mgr"
ARG REPO_NAME__CAL_MGR="nwm-cal-mgr"
ARG REPO_NAME__MSW_MGR="nwm-msw-mgr"
ARG REPO_NAME__REGION_MGR="nwm-region-mgr"
ARG REPO_NAME__REGION_MGR_UNDERSCORES="nwm_region_mgr"
ARG REPO_NAME__VERF_MGR="nwm-verf"
ARG REPO_NAME__EVAL_MGR="nwm-eval-mgr"
ARG MSWM_MODULE_PARAMETER_FILES="/ngen-app/${REPO_NAME__MSW_MGR}/src/mswm/module_parameter_files"
### For Python 3.10 base image (ngen ghcr ngen:latest as of 10/28/25)
# ARG PYTHON_VERSION_STR="python3.10"
### For Python 3.11 base image (ngen development as of 10/28/25)
ARG PYTHON_VERSION_STR="python3.11"


### Activate the venv
ENV PATH="${PYTHON_ENV}:${PATH}"
RUN pip install --upgrade pip


##############################
##### Forecast Manager

## From GitHub
RUN pip install "${GITHUB_ORG_URL}/${REPO_NAME__FCST_MGR}/archive/${REPO_TAG__FCST_MGR}.tar.gz"

## From local
# COPY "${REPO_NAME__FCST_MGR}/" "/tmp/${REPO_NAME__FCST_MGR}/"
# RUN pip install "/tmp/${REPO_NAME__FCST_MGR}" && rm -rf "/tmp/${REPO_NAME__FCST_MGR}"
### NOTE the following alternate method of mounting the source code rather than temporarily copying it into the image
### was not working 202151031 due to error: "Cannot update time stamp of directory 'python/nwm_fcst_mgr.egg-info'"
### RUN --mount=type=bind,source=./${REPO_NAME__FCST_MGR},target=/tmp/${REPO_NAME__FCST_MGR} pip install "/tmp/${REPO_NAME__FCST_MGR}"


##############################
##### Model Setup Workflow Manager

## From GitHub
RUN pip install "${GITHUB_ORG_URL}/${REPO_NAME__MSW_MGR}/archive/${REPO_TAG__MSW_MGR}.tar.gz"
RUN mkdir -p `dirname ${MSWM_MODULE_PARAMETER_FILES}`

## From local
# COPY "${REPO_NAME__MSW_MGR}/" "/tmp/${REPO_NAME__MSW_MGR}/"
# RUN pip install "/tmp/${REPO_NAME__MSW_MGR}" && rm -rf "/tmp/${REPO_NAME__MSW_MGR}"

## Either way, do the symlink to module_parameter_files. TODO improve this
RUN mkdir -p "`dirname ${MSWM_MODULE_PARAMETER_FILES}`" && ln -s "/ngen-app/ngen-python/lib/${PYTHON_VERSION_STR}/site-packages/mswm/module_parameter_files" "${MSWM_MODULE_PARAMETER_FILES}"


##############################
#### Calibration Manager (TODO have executable py scripts come included with pip install)

## From GitHub
RUN pip install "${GITHUB_ORG_URL}/${REPO_NAME__CAL_MGR}/archive/${REPO_TAG__CAL_MGR}.tar.gz#subdirectory=python/calib"
RUN pip install "${GITHUB_ORG_URL}/${REPO_NAME__CAL_MGR}/archive/${REPO_TAG__CAL_MGR}.tar.gz#subdirectory=python/config"
ADD "${GITHUBUSERCONTENT_ORG_URL}/${REPO_NAME__CAL_MGR}/${REPO_TAG__CAL_MGR}/python/calibration.py" "/ngen-app/bin/"
ADD "${GITHUBUSERCONTENT_ORG_URL}/${REPO_NAME__CAL_MGR}/${REPO_TAG__CAL_MGR}/python/validation.py" "/ngen-app/bin/"
ADD "${GITHUBUSERCONTENT_ORG_URL}/${REPO_NAME__CAL_MGR}/${REPO_TAG__CAL_MGR}/python/validation_iteration.py" "/ngen-app/bin/"

## From local
# COPY "${REPO_NAME__CAL_MGR}/" "/tmp/${REPO_NAME__CAL_MGR}/"
# RUN \
#     pip install "/tmp/${REPO_NAME__CAL_MGR}/python/calib" && \
#     pip install "/tmp/${REPO_NAME__CAL_MGR}/python/config" && \
#     rm -rf "/tmp/${REPO_NAME__CAL_MGR}/"
# ADD "${REPO_NAME__CAL_MGR}/python/calibration.py" "/ngen-app/bin/"
# ADD "${REPO_NAME__CAL_MGR}/python/validation.py" "/ngen-app/bin/"
# ADD "${REPO_NAME__CAL_MGR}/python/validation_iteration.py" "/ngen-app/bin/"


##############################
#### Region Manager

## From GitHub
# RUN pip install "nwm_region_mgr[parreg] @ git+${GITHUB_ORG_URL}/${REPO_NAME__REGION_MGR}@${REPO_TAG__REGION_MGR}"

## From local
COPY --exclude=/data . "/ngen-app/${REPO_NAME__REGION_MGR}/" 

RUN \
    pip install nwm-region-mgr[parreg] "/ngen-app/${REPO_NAME__REGION_MGR}"

    
##############################
#### Verification Manager

## From GitHub
RUN pip install "${REPO_NAME__VERF_MGR} @ git+${GITHUB_ORG_URL}/${REPO_NAME__VERF_MGR}@${REPO_TAG__VERF_MGR}"


##############################
#### Evaluation Manager

## From GitHub
RUN pip install "nwm_eval @ git+${GITHUB_ORG_URL}/${REPO_NAME__EVAL_MGR}@${REPO_TAG__EVAL_MGR}"

RUN pip install "shapely<2.0"