# 
# TODO add {}_git_info.json for each dependency repo (other repos do this in their Dockerfile).
# TODO have remote vs local be parameterized in config file rather than requiring switching comment blocks here.
# 


ARG NGEN_BASE_IMAGE="ghcr.io/ngwpc/ngen:latest"
FROM $NGEN_BASE_IMAGE

### Additional user args, these have to be after the FROM
ARG REPO_TAG__FCST_MGR
ARG REPO_TAG__MSW_MGR
ARG REPO_TAG__CAL_MGR
ARG REPO_TAG__REGION_MGR
ARG REPO_TAG__VERF_MGR
ARG REPO_TAG__EVAL_MGR
ARG REPO_TAG__DATA_ASSIM_ENGINE

### Static args
ARG PYTHON_ENV="/ngen-app/ngen-python/bin"
ARG GITHUB_ORG_URL="https://github.com/NGWPC"
ARG GITHUBUSERCONTENT_ORG_URL="https://raw.githubusercontent.com/NGWPC"
ARG REPO_NAME__FCST_MGR="nwm-fcst-mgr"
ARG REPO_NAME__CAL_MGR="nwm-cal-mgr"
ARG REPO_NAME__MSW_MGR="nwm-msw-mgr"
ARG REPO_NAME__REGION_MGR="nwm-region-mgr"
ARG REPO_NAME__VERF_MGR="nwm-verf"
ARG REPO_NAME__EVAL_MGR="nwm-eval-mgr"
ARG REPO_NAME__DATA_ASSIM_ENGINE="data-assimilation-engine"
ARG MSWM_MODULE_PARAMETER_FILES="/ngen-app/${REPO_NAME__MSW_MGR}/src/mswm/module_parameter_files"
### For Python 3.10 base image (ngen ghcr ngen:latest as of 10/28/25)
# ARG PYTHON_VERSION_STR="python3.10"
### For Python 3.11 base image (ngen development as of 10/28/25)
ARG PYTHON_VERSION_STR="python3.11"

ENV PIP_NO_CACHE_DIR=1

COPY nwm-rte/add_git_info.py .


### Activate the venv
ENV PATH="${PYTHON_ENV}:${PATH}"
RUN pip install --upgrade pip


##############################
##### Forecast Manager

## From GitHub
RUN pip install "${GITHUB_ORG_URL}/${REPO_NAME__FCST_MGR}/archive/${REPO_TAG__FCST_MGR}.tar.gz"

## From local
# COPY "${REPO_NAME__FCST_MGR}/" "/tmp/${REPO_NAME__FCST_MGR}/"
# RUN pip install "/tmp/${REPO_NAME__FCST_MGR}" && rm -rf "/tmp/${REPO_NAME__FCST_MGR}"
### NOTE the following alternate method of mounting the source code rather than temporarily copying it into the image
### was not working 202151031 due to error: "Cannot update time stamp of directory 'python/nwm_fcst_mgr.egg-info'"
### RUN --mount=type=bind,source=./${REPO_NAME__FCST_MGR},target=/tmp/${REPO_NAME__FCST_MGR} pip install "/tmp/${REPO_NAME__FCST_MGR}"


##############################
##### Model Setup Workflow Manager

## From GitHub
RUN pip install "${GITHUB_ORG_URL}/${REPO_NAME__MSW_MGR}/archive/${REPO_TAG__MSW_MGR}.tar.gz"
RUN mkdir -p `dirname ${MSWM_MODULE_PARAMETER_FILES}`

## From local
# COPY "${REPO_NAME__MSW_MGR}/" "/tmp/${REPO_NAME__MSW_MGR}/"
# RUN pip install "/tmp/${REPO_NAME__MSW_MGR}" && rm -rf "/tmp/${REPO_NAME__MSW_MGR}"

## Either way, do the symlink to module_parameter_files. TODO improve this
RUN mkdir -p "`dirname ${MSWM_MODULE_PARAMETER_FILES}`" && ln -s "/ngen-app/ngen-python/lib/${PYTHON_VERSION_STR}/site-packages/mswm/module_parameter_files" "${MSWM_MODULE_PARAMETER_FILES}"


##############################
#### Calibration Manager (TODO have executable py scripts come included with pip install)

## From GitHub
RUN pip install "${GITHUB_ORG_URL}/${REPO_NAME__CAL_MGR}/archive/${REPO_TAG__CAL_MGR}.tar.gz#subdirectory=python/calib"
RUN pip install "${GITHUB_ORG_URL}/${REPO_NAME__CAL_MGR}/archive/${REPO_TAG__CAL_MGR}.tar.gz#subdirectory=python/config"
ADD "${GITHUBUSERCONTENT_ORG_URL}/${REPO_NAME__CAL_MGR}/${REPO_TAG__CAL_MGR}/python/calibration.py" "/ngen-app/bin/"
ADD "${GITHUBUSERCONTENT_ORG_URL}/${REPO_NAME__CAL_MGR}/${REPO_TAG__CAL_MGR}/python/validation.py" "/ngen-app/bin/"
ADD "${GITHUBUSERCONTENT_ORG_URL}/${REPO_NAME__CAL_MGR}/${REPO_TAG__CAL_MGR}/python/validation_iteration.py" "/ngen-app/bin/"

## From local
# COPY "${REPO_NAME__CAL_MGR}/" "/tmp/${REPO_NAME__CAL_MGR}/"
# RUN \
#     pip install "/tmp/${REPO_NAME__CAL_MGR}/python/calib" && \
#     pip install "/tmp/${REPO_NAME__CAL_MGR}/python/config" && \
#     rm -rf "/tmp/${REPO_NAME__CAL_MGR}/"
# ADD "${REPO_NAME__CAL_MGR}/python/calibration.py" "/ngen-app/bin/"
# ADD "${REPO_NAME__CAL_MGR}/python/validation.py" "/ngen-app/bin/"
# ADD "${REPO_NAME__CAL_MGR}/python/validation_iteration.py" "/ngen-app/bin/"


##############################
#### Region Manager

## From GitHub
### TODO this currently uses shapely 2. Need to either upgrade ngen's shapely, or downgrade this package's shapely to <2
RUN pip install "nwm_region_mgr[parreg] @ git+${GITHUB_ORG_URL}/${REPO_NAME__REGION_MGR}@${REPO_TAG__REGION_MGR}"

## From local
# COPY "${REPO_NAME__REGION_MGR}/" "/tmp/${REPO_NAME__REGION_MGR}/"
# RUN \
#     pip install "/tmp/${REPO_NAME__REGION_MGR}[parreg]" && \
#     rm -rf "/tmp/${REPO_NAME__REGION_MGR}/"


##############################
#### Verification Manager

# Problem: dependency teehr (https://github.com/RTIInternational/teehr) calls for min version 1.6.5 for netCDF4. ngen-forcing throws segfaults at 1.6.4+

### Solution A: Fork teehr and lower the netCDF4 version in the fork (here using local changes to simulate a fork)
### To set this up (from ngwpc repo root):
###     Run: git clone git@github.com:RTIInternational/teehr.git
###     Run: ( cd teehr && git checkout v0.5.2 )
###     Set local teehr's pyproject.toml with netcdf4 = "1.6.3"
###     Set local nwm-verf's pyproject.toml with "teehr" (no specific version for teehr so it will accept the local teehr mod)
# COPY "teehr/" "/tmp/teehr/"
# RUN pip install "/tmp/teehr" && rm -rf "/tmp/teehr/"
# COPY "${REPO_NAME__VERF_MGR}/" "/tmp/${REPO_NAME__VERF_MGR}/"
# RUN pip install "/tmp/${REPO_NAME__VERF_MGR}" && rm -rf "/tmp/${REPO_NAME__VERF_MGR}/"

### Solution B: After installing RTIInternational/teehr (upstream), re-install netCDF4 version 1.6.3.  This may result in conflict messages when installing tehr itself.
### To set this up:
###     No action needed other than pointing to the right testing branch of nwm-verf
RUN pip install "nwm.verf @ git+${GITHUB_ORG_URL}/${REPO_NAME__VERF_MGR}@${REPO_TAG__VERF_MGR}"
RUN pip install netCDF4==1.6.3


##############################
#### Evaluation Manager

## From GitHub
### TODO this currently uses shapely 2. Need to either upgrade ngen's shapely, or downgrade this package's shapely to <2
# RUN pip install "nwm_eval @ git+${GITHUB_ORG_URL}/${REPO_NAME__EVAL_MGR}@${REPO_TAG__EVAL_MGR}"
RUN pip install "git+${GITHUB_ORG_URL}/${REPO_NAME__EVAL_MGR}@${REPO_TAG__EVAL_MGR}"


##############################
#### Data Assimilation Engine

## From GitHub
### TODO this currently uses shapely 2. Need to either upgrade ngen's shapely, or downgrade this package's shapely to <2
# RUN pip install "data_assimilation_engine @ git+${GITHUB_ORG_URL}/${REPO_NAME__DATA_ASSIM_ENGINE}@${REPO_TAG__DATA_ASSIM_ENGINE}"
RUN pip install "git+${GITHUB_ORG_URL}/${REPO_NAME__DATA_ASSIM_ENGINE}@${REPO_TAG__DATA_ASSIM_ENGINE}"


# ##############################
# ##### For testing shapely 2 upgrade, below re-installs ngen-forcing. Not to be used in production.

# ## From GitHub
# ##  For ngen-forcing, these methods of pip install directly from GitHub don't seem to (re)install the various packages within the repo properly, so use git clone for now
# ##      RUN pip install "${GITHUB_ORG_URL}/ngen-forcing/archive/maxkipp-ngwpc-8941-upgrade-shapely-2.tar.gz"
# ##      RUN pip install "git+${GITHUB_ORG_URL}/ngen-forcing@maxkipp-ngwpc-8941-upgrade-shapely-2"
# RUN \
#     mkdir -p /tmp && cd /tmp && \
#     git clone --depth 1 --branch "maxkipp-ngwpc-8941-upgrade-shapely-2" "${GITHUB_ORG_URL}/ngen-forcing.git" && \
#     pip install ./ngen-forcing && \
#     rm -rf ./ngen-forcing

## From local
# COPY "ngen-forcing/" "/tmp/ngen-forcing/"
# RUN python add_git_info.py --local_repo_path "/tmp/ngen-forcing" --output_dir "/ngen-app/" && \
#     pip install "/tmp/ngen-forcing" && rm -rf "/tmp/ngen-forcing/"
